// <auto-generated />
using System;
using DataAccess.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(Proect1Context))]
    [Migration("20251106091239_MigratonName")]
    partial class MigratonName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.ДолгиПоДежурствам", b =>
                {
                    b.Property<int>("IdДолга")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_долга");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdДолга"));

                    b.Property<int?>("IdОтработочногоДежурства")
                        .HasColumnType("int")
                        .HasColumnName("ID_отработочного_дежурства");

                    b.Property<int>("IdПользователя")
                        .HasColumnType("int")
                        .HasColumnName("ID_пользователя");

                    b.Property<int>("IdПропущенногоДежурства")
                        .HasColumnType("int")
                        .HasColumnName("ID_пропущенного_дежурства");

                    b.Property<DateTime?>("ДатаЗакрытия")
                        .HasColumnType("datetime2")
                        .HasColumnName("Дата_закрытия");

                    b.Property<DateTime?>("ДатаСоздания")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("Дата_создания")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("НоваяДата")
                        .HasColumnType("date")
                        .HasColumnName("Новая_дата");

                    b.Property<string>("Статус")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("ожидание");

                    b.HasKey("IdДолга")
                        .HasName("PK__ДолгиПоД__4C9FBB725845CDFC");

                    b.HasIndex("IdОтработочногоДежурства");

                    b.HasIndex("IdПользователя");

                    b.HasIndex("IdПропущенногоДежурства");

                    b.ToTable("ДолгиПоДежурствам", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ЗапросыНаЗамену", b =>
                {
                    b.Property<int>("IdЗапроса")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_запроса");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdЗапроса"));

                    b.Property<int>("IdДежурства")
                        .HasColumnType("int")
                        .HasColumnName("ID_дежурства");

                    b.Property<int>("IdЗаменяющего")
                        .HasColumnType("int")
                        .HasColumnName("ID_заменяющего");

                    b.Property<int>("IdЗапрашивающего")
                        .HasColumnType("int")
                        .HasColumnName("ID_запрашивающего");

                    b.Property<DateTime?>("ДатаОбновления")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("Дата_обновления")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("ДатаСоздания")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("Дата_создания")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("КомментарийЗапроса")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Комментарий_запроса");

                    b.Property<string>("КомментарийОтвета")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Комментарий_ответа");

                    b.Property<DateOnly?>("НоваяДата")
                        .HasColumnType("date")
                        .HasColumnName("Новая_дата");

                    b.Property<int?>("Одобрил")
                        .HasColumnType("int");

                    b.Property<string>("Статус")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("ожидание");

                    b.HasKey("IdЗапроса")
                        .HasName("PK__ЗапросыН__01448438A41999EF");

                    b.HasIndex("IdДежурства");

                    b.HasIndex("IdЗаменяющего");

                    b.HasIndex("IdЗапрашивающего");

                    b.HasIndex("Одобрил");

                    b.ToTable("ЗапросыНаЗамену", (string)null);
                });

            modelBuilder.Entity("Domain.Models.НазначенияРолей", b =>
                {
                    b.Property<int>("IdНазначения")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_назначения");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdНазначения"));

                    b.Property<int>("IdПользователя")
                        .HasColumnType("int")
                        .HasColumnName("ID_пользователя");

                    b.Property<int>("IdРоли")
                        .HasColumnType("int")
                        .HasColumnName("ID_роли");

                    b.Property<DateTime?>("ДатаНазначения")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("Дата_назначения")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("Назначил")
                        .HasColumnType("int");

                    b.HasKey("IdНазначения")
                        .HasName("PK__Назначен__7034F95F734DA23D");

                    b.HasIndex("IdПользователя");

                    b.HasIndex("IdРоли");

                    b.HasIndex("Назначил");

                    b.ToTable("НазначенияРолей", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Пользователи", b =>
                {
                    b.Property<int>("IdПользователя")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_пользователя");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdПользователя"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("Активен")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ДатаОбновления")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("Дата_обновления")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("ДатаСоздания")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("Дата_создания")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Имя")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Логин")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Пароль")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Телефон")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Фамилия")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdПользователя")
                        .HasName("PK__Пользова__B1AC0CDEB0127D7E");

                    b.HasIndex(new[] { "Email" }, "UQ__Пользова__A9D105347D5A58FC")
                        .IsUnique();

                    b.HasIndex(new[] { "Логин" }, "UQ__Пользова__BC2217D3375C02AA")
                        .IsUnique();

                    b.ToTable("Пользователи", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Пропуски", b =>
                {
                    b.Property<int>("IdПропуска")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_пропуска");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdПропуска"));

                    b.Property<int>("IdГруппы")
                        .HasColumnType("int")
                        .HasColumnName("ID_группы");

                    b.Property<int>("IdПользователя")
                        .HasColumnType("int")
                        .HasColumnName("ID_пользователя");

                    b.Property<DateOnly>("ДатаПропуска")
                        .HasColumnType("date")
                        .HasColumnName("Дата_пропуска");

                    b.Property<DateTime?>("ДатаСоздания")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("Дата_создания")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Описание")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Отметил")
                        .HasColumnType("int");

                    b.Property<string>("Причина")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("Уважительная")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("IdПропуска")
                        .HasName("PK__Пропуски__77AC52A5027D18D2");

                    b.HasIndex("IdГруппы");

                    b.HasIndex("IdПользователя");

                    b.HasIndex("Отметил");

                    b.ToTable("Пропуски", (string)null);
                });

            modelBuilder.Entity("Domain.Models.РасписаниеДежурств", b =>
                {
                    b.Property<int>("IdРасписания")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_расписания");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdРасписания"));

                    b.Property<int>("IdГруппы")
                        .HasColumnType("int")
                        .HasColumnName("ID_группы");

                    b.Property<int>("IdДежурного")
                        .HasColumnType("int")
                        .HasColumnName("ID_дежурного");

                    b.Property<DateOnly>("ДатаДежурства")
                        .HasColumnType("date")
                        .HasColumnName("Дата_дежурства");

                    b.Property<DateTime?>("ДатаОбновления")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("Дата_обновления")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("ДатаСоздания")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("Дата_создания")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("Создал")
                        .HasColumnType("int");

                    b.Property<string>("Статус")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("запланировано");

                    b.HasKey("IdРасписания")
                        .HasName("PK__Расписан__6BE45D70D9EE56FF");

                    b.HasIndex("IdГруппы");

                    b.HasIndex("IdДежурного");

                    b.HasIndex("Создал");

                    b.ToTable("РасписаниеДежурств", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Роли", b =>
                {
                    b.Property<int>("IdРоли")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_роли");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdРоли"));

                    b.Property<DateTime?>("ДатаСоздания")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("Дата_создания")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("НазваниеРоли")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Название_роли");

                    b.Property<string>("Описание")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdРоли")
                        .HasName("PK__Роли__11CE7F093BE2EC30");

                    b.HasIndex(new[] { "НазваниеРоли" }, "UQ__Роли__927FA07BDADF8E5A")
                        .IsUnique();

                    b.ToTable("Роли", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Уведомления", b =>
                {
                    b.Property<int>("IdУведомления")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_уведомления");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdУведомления"));

                    b.Property<int>("IdПользователя")
                        .HasColumnType("int")
                        .HasColumnName("ID_пользователя");

                    b.Property<DateTime?>("ДатаОтправки")
                        .HasColumnType("datetime2")
                        .HasColumnName("Дата_отправки");

                    b.Property<DateTime?>("ДатаСоздания")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("Дата_создания")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Заголовок")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("Прочитано")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Сообщение")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ТипУведомления")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Тип_уведомления");

                    b.HasKey("IdУведомления")
                        .HasName("PK__Уведомле__3DA678172E68D11A");

                    b.HasIndex("IdПользователя");

                    b.ToTable("Уведомления", (string)null);
                });

            modelBuilder.Entity("Domain.Models.УчебныеГруппы", b =>
                {
                    b.Property<int>("IdГруппы")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_группы");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdГруппы"));

                    b.Property<DateTime?>("ДатаСоздания")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("Дата_создания")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("Курс")
                        .HasColumnType("int");

                    b.Property<string>("НазваниеГруппы")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Название_группы");

                    b.Property<string>("Факультет")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdГруппы")
                        .HasName("PK__УчебныеГ__7EC7037DD053D9CE");

                    b.HasIndex(new[] { "НазваниеГруппы" }, "UQ__УчебныеГ__913C6830AB51EB2E")
                        .IsUnique();

                    b.ToTable("УчебныеГруппы", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ЧленствоВгруппах", b =>
                {
                    b.Property<int>("IdЧленства")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_членства");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdЧленства"));

                    b.Property<int>("IdГруппы")
                        .HasColumnType("int")
                        .HasColumnName("ID_группы");

                    b.Property<int>("IdПользователя")
                        .HasColumnType("int")
                        .HasColumnName("ID_пользователя");

                    b.Property<bool?>("Активен")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ДатаВступления")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("Дата_вступления")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("IdЧленства")
                        .HasName("PK__Членство__ED525EA0621731A9");

                    b.HasIndex("IdГруппы");

                    b.HasIndex("IdПользователя");

                    b.ToTable("ЧленствоВГруппах", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ДолгиПоДежурствам", b =>
                {
                    b.HasOne("Domain.Models.РасписаниеДежурств", "IdОтработочногоДежурстваNavigation")
                        .WithMany("ДолгиПоДежурствамIdОтработочногоДежурстваNavigations")
                        .HasForeignKey("IdОтработочногоДежурства")
                        .HasConstraintName("FK__ДолгиПоДе__ID_от__6B24EA82");

                    b.HasOne("Domain.Models.Пользователи", "IdПользователяNavigation")
                        .WithMany("ДолгиПоДежурствамs")
                        .HasForeignKey("IdПользователя")
                        .IsRequired()
                        .HasConstraintName("FK__ДолгиПоДе__ID_по__68487DD7");

                    b.HasOne("Domain.Models.РасписаниеДежурств", "IdПропущенногоДежурстваNavigation")
                        .WithMany("ДолгиПоДежурствамIdПропущенногоДежурстваNavigations")
                        .HasForeignKey("IdПропущенногоДежурства")
                        .IsRequired()
                        .HasConstraintName("FK__ДолгиПоДе__ID_пр__693CA210");

                    b.Navigation("IdОтработочногоДежурстваNavigation");

                    b.Navigation("IdПользователяNavigation");

                    b.Navigation("IdПропущенногоДежурстваNavigation");
                });

            modelBuilder.Entity("Domain.Models.ЗапросыНаЗамену", b =>
                {
                    b.HasOne("Domain.Models.РасписаниеДежурств", "IdДежурстваNavigation")
                        .WithMany("ЗапросыНаЗаменуs")
                        .HasForeignKey("IdДежурства")
                        .IsRequired()
                        .HasConstraintName("FK__ЗапросыНа__ID_де__619B8048");

                    b.HasOne("Domain.Models.Пользователи", "IdЗаменяющегоNavigation")
                        .WithMany("ЗапросыНаЗаменуIdЗаменяющегоNavigations")
                        .HasForeignKey("IdЗаменяющего")
                        .IsRequired()
                        .HasConstraintName("FK__ЗапросыНа__ID_за__60A75C0F");

                    b.HasOne("Domain.Models.Пользователи", "IdЗапрашивающегоNavigation")
                        .WithMany("ЗапросыНаЗаменуIdЗапрашивающегоNavigations")
                        .HasForeignKey("IdЗапрашивающего")
                        .IsRequired()
                        .HasConstraintName("FK__ЗапросыНа__ID_за__5FB337D6");

                    b.HasOne("Domain.Models.Пользователи", "ОдобрилNavigation")
                        .WithMany("ЗапросыНаЗаменуОдобрилNavigations")
                        .HasForeignKey("Одобрил")
                        .HasConstraintName("FK__ЗапросыНа__Одобр__6383C8BA");

                    b.Navigation("IdДежурстваNavigation");

                    b.Navigation("IdЗаменяющегоNavigation");

                    b.Navigation("IdЗапрашивающегоNavigation");

                    b.Navigation("ОдобрилNavigation");
                });

            modelBuilder.Entity("Domain.Models.НазначенияРолей", b =>
                {
                    b.HasOne("Domain.Models.Пользователи", "IdПользователяNavigation")
                        .WithMany("НазначенияРолейIdПользователяNavigations")
                        .HasForeignKey("IdПользователя")
                        .IsRequired()
                        .HasConstraintName("FK__Назначени__ID_по__4222D4EF");

                    b.HasOne("Domain.Models.Роли", "IdРолиNavigation")
                        .WithMany("НазначенияРолейs")
                        .HasForeignKey("IdРоли")
                        .IsRequired()
                        .HasConstraintName("FK__Назначени__ID_ро__4316F928");

                    b.HasOne("Domain.Models.Пользователи", "НазначилNavigation")
                        .WithMany("НазначенияРолейНазначилNavigations")
                        .HasForeignKey("Назначил")
                        .HasConstraintName("FK__Назначени__Назна__44FF419A");

                    b.Navigation("IdПользователяNavigation");

                    b.Navigation("IdРолиNavigation");

                    b.Navigation("НазначилNavigation");
                });

            modelBuilder.Entity("Domain.Models.Пропуски", b =>
                {
                    b.HasOne("Domain.Models.УчебныеГруппы", "IdГруппыNavigation")
                        .WithMany("Пропускиs")
                        .HasForeignKey("IdГруппы")
                        .IsRequired()
                        .HasConstraintName("FK__Пропуски__ID_гру__59FA5E80");

                    b.HasOne("Domain.Models.Пользователи", "IdПользователяNavigation")
                        .WithMany("ПропускиIdПользователяNavigations")
                        .HasForeignKey("IdПользователя")
                        .IsRequired()
                        .HasConstraintName("FK__Пропуски__ID_пол__59063A47");

                    b.HasOne("Domain.Models.Пользователи", "ОтметилNavigation")
                        .WithMany("ПропускиОтметилNavigations")
                        .HasForeignKey("Отметил")
                        .IsRequired()
                        .HasConstraintName("FK__Пропуски__Отмети__5BE2A6F2");

                    b.Navigation("IdГруппыNavigation");

                    b.Navigation("IdПользователяNavigation");

                    b.Navigation("ОтметилNavigation");
                });

            modelBuilder.Entity("Domain.Models.РасписаниеДежурств", b =>
                {
                    b.HasOne("Domain.Models.УчебныеГруппы", "IdГруппыNavigation")
                        .WithMany("РасписаниеДежурствs")
                        .HasForeignKey("IdГруппы")
                        .IsRequired()
                        .HasConstraintName("FK__Расписани__ID_гр__5165187F");

                    b.HasOne("Domain.Models.Пользователи", "IdДежурногоNavigation")
                        .WithMany("РасписаниеДежурствIdДежурногоNavigations")
                        .HasForeignKey("IdДежурного")
                        .IsRequired()
                        .HasConstraintName("FK__Расписани__ID_де__52593CB8");

                    b.HasOne("Domain.Models.Пользователи", "СоздалNavigation")
                        .WithMany("РасписаниеДежурствСоздалNavigations")
                        .HasForeignKey("Создал")
                        .IsRequired()
                        .HasConstraintName("FK__Расписани__Созда__5441852A");

                    b.Navigation("IdГруппыNavigation");

                    b.Navigation("IdДежурногоNavigation");

                    b.Navigation("СоздалNavigation");
                });

            modelBuilder.Entity("Domain.Models.Уведомления", b =>
                {
                    b.HasOne("Domain.Models.Пользователи", "IdПользователяNavigation")
                        .WithMany("Уведомленияs")
                        .HasForeignKey("IdПользователя")
                        .IsRequired()
                        .HasConstraintName("FK__Уведомлен__ID_по__6EF57B66");

                    b.Navigation("IdПользователяNavigation");
                });

            modelBuilder.Entity("Domain.Models.ЧленствоВгруппах", b =>
                {
                    b.HasOne("Domain.Models.УчебныеГруппы", "IdГруппыNavigation")
                        .WithMany("ЧленствоВгруппахs")
                        .HasForeignKey("IdГруппы")
                        .IsRequired()
                        .HasConstraintName("FK__ЧленствоВ__ID_гр__4CA06362");

                    b.HasOne("Domain.Models.Пользователи", "IdПользователяNavigation")
                        .WithMany("ЧленствоВгруппахs")
                        .HasForeignKey("IdПользователя")
                        .IsRequired()
                        .HasConstraintName("FK__ЧленствоВ__ID_по__4BAC3F29");

                    b.Navigation("IdГруппыNavigation");

                    b.Navigation("IdПользователяNavigation");
                });

            modelBuilder.Entity("Domain.Models.Пользователи", b =>
                {
                    b.Navigation("ДолгиПоДежурствамs");

                    b.Navigation("ЗапросыНаЗаменуIdЗаменяющегоNavigations");

                    b.Navigation("ЗапросыНаЗаменуIdЗапрашивающегоNavigations");

                    b.Navigation("ЗапросыНаЗаменуОдобрилNavigations");

                    b.Navigation("НазначенияРолейIdПользователяNavigations");

                    b.Navigation("НазначенияРолейНазначилNavigations");

                    b.Navigation("ПропускиIdПользователяNavigations");

                    b.Navigation("ПропускиОтметилNavigations");

                    b.Navigation("РасписаниеДежурствIdДежурногоNavigations");

                    b.Navigation("РасписаниеДежурствСоздалNavigations");

                    b.Navigation("Уведомленияs");

                    b.Navigation("ЧленствоВгруппахs");
                });

            modelBuilder.Entity("Domain.Models.РасписаниеДежурств", b =>
                {
                    b.Navigation("ДолгиПоДежурствамIdОтработочногоДежурстваNavigations");

                    b.Navigation("ДолгиПоДежурствамIdПропущенногоДежурстваNavigations");

                    b.Navigation("ЗапросыНаЗаменуs");
                });

            modelBuilder.Entity("Domain.Models.Роли", b =>
                {
                    b.Navigation("НазначенияРолейs");
                });

            modelBuilder.Entity("Domain.Models.УчебныеГруппы", b =>
                {
                    b.Navigation("Пропускиs");

                    b.Navigation("РасписаниеДежурствs");

                    b.Navigation("ЧленствоВгруппахs");
                });
#pragma warning restore 612, 618
        }
    }
}
